/**
 * v1 에는 있었지만 v2 시맨틱 층(src/styles/**)에는 더 이상 존재하지 않는
 * 토큰 이름 86개 — git 히스토리(마지막으로 --tui-shadow-xl 을 가졌던
 * tokens.css, 커밋 45a789a 의 부모)에서 실측한 목록이다.
 *
 * 원래 .superpowers/sdd/2026-09-09-trust-ui-v2-docs-release/v1-only-tokens.txt
 * 를 직접 읽었는데, 그 디렉터리는 이 계획이 끝나면 통째로 사라지는
 * 임시 산출물이라 compat.css 와 무관한 이유로 테스트가 깨질 뻔했다.
 * 그래서 이 배열을 tests/tokens/ 아래 영구 픽스처로 옮겼다.
 *
 * 이 목록은 v1 이 고정된 과거 시점의 실측값이라 늘어나지 않는다 —
 * v2 에 토큰이 추가/삭제되어도 이 배열은 바뀌지 않는다.
 */
export const V1_ONLY_TOKENS = [
  '--tui-bg',
  '--tui-bg-hover',
  '--tui-bg-muted',
  '--tui-bg-subtle',
  '--tui-border',
  '--tui-border-focus',
  '--tui-border-hover',
  '--tui-danger-subtle',
  '--tui-danger-text',
  '--tui-duration-medium',
  '--tui-duration-slow',
  '--tui-ease-in-out',
  '--tui-ease-linear',
  '--tui-ease-spring',
  '--tui-focus-ring',
  '--tui-font-family',
  '--tui-font-mono',
  '--tui-font-size-2xl',
  '--tui-font-size-lg',
  '--tui-font-size-md',
  '--tui-font-size-sm',
  '--tui-font-size-xl',
  '--tui-font-size-xs',
  '--tui-font-weight-bold',
  '--tui-font-weight-medium',
  '--tui-font-weight-normal',
  '--tui-font-weight-semibold',
  '--tui-glass-bg',
  '--tui-glass-blur',
  '--tui-glass-border',
  '--tui-glass-shadow',
  '--tui-info',
  '--tui-info-hover',
  '--tui-info-subtle',
  '--tui-info-text',
  '--tui-inset-highlight',
  '--tui-letter-tight',
  '--tui-letter-tighter',
  '--tui-line-height',
  '--tui-overlay',
  '--tui-primary',
  '--tui-primary-active',
  '--tui-primary-hover',
  '--tui-primary-subtle',
  '--tui-primary-text',
  '--tui-radius-2xl',
  '--tui-radius-lg',
  '--tui-radius-md',
  '--tui-radius-sm',
  '--tui-radius-xl',
  '--tui-radius-xs',
  '--tui-secondary',
  '--tui-secondary-active',
  '--tui-secondary-hover',
  '--tui-secondary-subtle',
  '--tui-secondary-text',
  '--tui-shadow-lg',
  '--tui-shadow-md',
  '--tui-shadow-sm',
  '--tui-shadow-xl',
  '--tui-shadow-xs',
  '--tui-spacing-2xl',
  '--tui-spacing-3xl',
  '--tui-spacing-lg',
  '--tui-spacing-md',
  '--tui-spacing-sm',
  '--tui-spacing-xl',
  '--tui-spacing-xs',
  '--tui-success-hover',
  '--tui-success-subtle',
  '--tui-success-text',
  '--tui-text',
  '--tui-text-inverse',
  '--tui-text-muted',
  '--tui-text-secondary',
  '--tui-thumb-zone-height',
  '--tui-touch-target-comfortable',
  '--tui-touch-target-min',
  '--tui-transition',
  '--tui-transition-fast',
  '--tui-transition-shadow',
  '--tui-transition-slow',
  '--tui-transition-transform',
  '--tui-warning-hover',
  '--tui-warning-subtle',
  '--tui-warning-text',
];
